version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-nextjs
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_CONTENTFUL_SPACE_ID=${NEXT_PUBLIC_CONTENTFUL_SPACE_ID}
      - CONTENTFUL_ACCESS_TOKEN=${CONTENTFUL_ACCESS_TOKEN}
    restart: unless-stopped
    volumes:
      - ./public:/app/public:ro
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge
